/**
 * @file automate.c
 *
 * @brief This source file was generated by cantools version 40.2.1 Fri Nov  7 15:56:34 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "automate.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int automate_heart_beat_msg_pack(
    uint8_t *dst_p,
    const struct automate_heart_beat_msg_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->node_id, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u32(src_p->msg_count, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->msg_count, 8u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->msg_count, 16u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(src_p->msg_count, 24u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->health, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->stamp, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->stamp, 8u, 0xffu);

    return (8);
}

int automate_heart_beat_msg_unpack(
    struct automate_heart_beat_msg_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->node_id = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->msg_count = unpack_right_shift_u32(src_p[1], 0u, 0xffu);
    dst_p->msg_count |= unpack_left_shift_u32(src_p[2], 8u, 0xffu);
    dst_p->msg_count |= unpack_left_shift_u32(src_p[3], 16u, 0xffu);
    dst_p->msg_count |= unpack_left_shift_u32(src_p[4], 24u, 0xffu);
    dst_p->health = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->stamp = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->stamp |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int automate_heart_beat_msg_init(struct automate_heart_beat_msg_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct automate_heart_beat_msg_t));

    return 0;
}

uint8_t automate_heart_beat_msg_node_id_encode(double value)
{
    return (uint8_t)(value);
}

double automate_heart_beat_msg_node_id_decode(uint8_t value)
{
    return ((double)value);
}

bool automate_heart_beat_msg_node_id_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint32_t automate_heart_beat_msg_msg_count_encode(double value)
{
    return (uint32_t)(value);
}

double automate_heart_beat_msg_msg_count_decode(uint32_t value)
{
    return ((double)value);
}

bool automate_heart_beat_msg_msg_count_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint8_t automate_heart_beat_msg_health_encode(double value)
{
    return (uint8_t)(value);
}

double automate_heart_beat_msg_health_decode(uint8_t value)
{
    return ((double)value);
}

bool automate_heart_beat_msg_health_is_in_range(uint8_t value)
{
    return (value <= 5u);
}

uint16_t automate_heart_beat_msg_stamp_encode(double value)
{
    return (uint16_t)(value);
}

double automate_heart_beat_msg_stamp_decode(uint16_t value)
{
    return ((double)value);
}

bool automate_heart_beat_msg_stamp_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int automate_left_brake_cmd_pack(
    uint8_t *dst_p,
    const struct automate_left_brake_cmd_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->msg_id, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->stamp, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->stamp, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->brake_state, 0u, 0x01u);

    return (8);
}

int automate_left_brake_cmd_unpack(
    struct automate_left_brake_cmd_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->msg_id = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->stamp = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->stamp |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->brake_state = unpack_right_shift_u8(src_p[3], 0u, 0x01u);

    return (0);
}

int automate_left_brake_cmd_init(struct automate_left_brake_cmd_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct automate_left_brake_cmd_t));

    return 0;
}

uint8_t automate_left_brake_cmd_msg_id_encode(double value)
{
    return (uint8_t)(value);
}

double automate_left_brake_cmd_msg_id_decode(uint8_t value)
{
    return ((double)value);
}

bool automate_left_brake_cmd_msg_id_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t automate_left_brake_cmd_stamp_encode(double value)
{
    return (uint16_t)(value);
}

double automate_left_brake_cmd_stamp_decode(uint16_t value)
{
    return ((double)value);
}

bool automate_left_brake_cmd_stamp_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t automate_left_brake_cmd_brake_state_encode(double value)
{
    return (uint8_t)(value);
}

double automate_left_brake_cmd_brake_state_decode(uint8_t value)
{
    return ((double)value);
}

bool automate_left_brake_cmd_brake_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int automate_left_brake_msg_pack(
    uint8_t *dst_p,
    const struct automate_left_brake_msg_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->msg_id, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->stamp, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->stamp, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->brake_releasing, 0u, 0x01u);
    dst_p[3] |= pack_left_shift_u8(src_p->brake_released, 1u, 0x02u);
    dst_p[3] |= pack_left_shift_u8(src_p->brake_pushing, 2u, 0x04u);
    dst_p[3] |= pack_left_shift_u8(src_p->brake_pushed, 3u, 0x08u);
    dst_p[4] |= pack_left_shift_u16(src_p->time_to_end_operation, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->time_to_end_operation, 8u, 0xffu);

    return (8);
}

int automate_left_brake_msg_unpack(
    struct automate_left_brake_msg_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->msg_id = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->stamp = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->stamp |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->brake_releasing = unpack_right_shift_u8(src_p[3], 0u, 0x01u);
    dst_p->brake_released = unpack_right_shift_u8(src_p[3], 1u, 0x02u);
    dst_p->brake_pushing = unpack_right_shift_u8(src_p[3], 2u, 0x04u);
    dst_p->brake_pushed = unpack_right_shift_u8(src_p[3], 3u, 0x08u);
    dst_p->time_to_end_operation = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->time_to_end_operation |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);

    return (0);
}

int automate_left_brake_msg_init(struct automate_left_brake_msg_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct automate_left_brake_msg_t));

    return 0;
}

uint8_t automate_left_brake_msg_msg_id_encode(double value)
{
    return (uint8_t)(value);
}

double automate_left_brake_msg_msg_id_decode(uint8_t value)
{
    return ((double)value);
}

bool automate_left_brake_msg_msg_id_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t automate_left_brake_msg_stamp_encode(double value)
{
    return (uint16_t)(value);
}

double automate_left_brake_msg_stamp_decode(uint16_t value)
{
    return ((double)value);
}

bool automate_left_brake_msg_stamp_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t automate_left_brake_msg_brake_releasing_encode(double value)
{
    return (uint8_t)(value);
}

double automate_left_brake_msg_brake_releasing_decode(uint8_t value)
{
    return ((double)value);
}

bool automate_left_brake_msg_brake_releasing_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t automate_left_brake_msg_brake_released_encode(double value)
{
    return (uint8_t)(value);
}

double automate_left_brake_msg_brake_released_decode(uint8_t value)
{
    return ((double)value);
}

bool automate_left_brake_msg_brake_released_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t automate_left_brake_msg_brake_pushing_encode(double value)
{
    return (uint8_t)(value);
}

double automate_left_brake_msg_brake_pushing_decode(uint8_t value)
{
    return ((double)value);
}

bool automate_left_brake_msg_brake_pushing_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t automate_left_brake_msg_brake_pushed_encode(double value)
{
    return (uint8_t)(value);
}

double automate_left_brake_msg_brake_pushed_decode(uint8_t value)
{
    return ((double)value);
}

bool automate_left_brake_msg_brake_pushed_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t automate_left_brake_msg_time_to_end_operation_encode(double value)
{
    return (uint16_t)(value);
}

double automate_left_brake_msg_time_to_end_operation_decode(uint16_t value)
{
    return ((double)value);
}

bool automate_left_brake_msg_time_to_end_operation_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}
