/**
 * @file automate.h
 *
 * @brief This header file was generated by cantools version 40.2.1 Fri Nov  7 15:56:34 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef AUTOMATE_H
#define AUTOMATE_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define AUTOMATE_HEART_BEAT_MSG_FRAME_ID (0x1800ad00u)
#define AUTOMATE_LEFT_BRAKE_CMD_FRAME_ID (0x1800ad09u)
#define AUTOMATE_LEFT_BRAKE_MSG_FRAME_ID (0x1800ad0au)

/* Frame lengths in bytes. */
#define AUTOMATE_HEART_BEAT_MSG_LENGTH (8u)
#define AUTOMATE_LEFT_BRAKE_CMD_LENGTH (8u)
#define AUTOMATE_LEFT_BRAKE_MSG_LENGTH (8u)

/* Extended or standard frame types. */
#define AUTOMATE_HEART_BEAT_MSG_IS_EXTENDED (1)
#define AUTOMATE_LEFT_BRAKE_CMD_IS_EXTENDED (1)
#define AUTOMATE_LEFT_BRAKE_MSG_IS_EXTENDED (1)

/* Frame cycle times in milliseconds. */
#define AUTOMATE_HEART_BEAT_MSG_CYCLE_TIME_MS (50u)
#define AUTOMATE_LEFT_BRAKE_CMD_CYCLE_TIME_MS (100u)

/* Signal choices. */
#define AUTOMATE_HEART_BEAT_MSG_HEALTH_OFF_CHOICE (0u)
#define AUTOMATE_HEART_BEAT_MSG_HEALTH_ON_CHOICE (1u)
#define AUTOMATE_HEART_BEAT_MSG_HEALTH_INIT_CHOICE (2u)
#define AUTOMATE_HEART_BEAT_MSG_HEALTH_WARNING_CHOICE (3u)
#define AUTOMATE_HEART_BEAT_MSG_HEALTH_FAILURE_CHOICE (4u)
#define AUTOMATE_HEART_BEAT_MSG_HEALTH_CRITICAL_FAILURE_CHOICE (5u)

#define AUTOMATE_LEFT_BRAKE_CMD_BRAKE_STATE_PUSH_CHOICE (0u)
#define AUTOMATE_LEFT_BRAKE_CMD_BRAKE_STATE_RELEASE_CHOICE (1u)

/* Frame Names. */
#define AUTOMATE_HEART_BEAT_MSG_NAME "Heart_Beat_MSG"
#define AUTOMATE_LEFT_BRAKE_CMD_NAME "Left_Brake_CMD"
#define AUTOMATE_LEFT_BRAKE_MSG_NAME "Left_Brake_MSG"

/* Signal Names. */
#define AUTOMATE_HEART_BEAT_MSG_NODE_ID_NAME "Node_id"
#define AUTOMATE_HEART_BEAT_MSG_MSG_COUNT_NAME "MSG_Count"
#define AUTOMATE_HEART_BEAT_MSG_HEALTH_NAME "Health"
#define AUTOMATE_HEART_BEAT_MSG_STAMP_NAME "Stamp"
#define AUTOMATE_LEFT_BRAKE_CMD_MSG_ID_NAME "MSG_Id"
#define AUTOMATE_LEFT_BRAKE_CMD_STAMP_NAME "Stamp"
#define AUTOMATE_LEFT_BRAKE_CMD_BRAKE_STATE_NAME "Brake_State"
#define AUTOMATE_LEFT_BRAKE_MSG_MSG_ID_NAME "MSG_Id"
#define AUTOMATE_LEFT_BRAKE_MSG_STAMP_NAME "Stamp"
#define AUTOMATE_LEFT_BRAKE_MSG_BRAKE_RELEASING_NAME "Brake_Releasing"
#define AUTOMATE_LEFT_BRAKE_MSG_BRAKE_RELEASED_NAME "Brake_Released"
#define AUTOMATE_LEFT_BRAKE_MSG_BRAKE_PUSHING_NAME "Brake_Pushing"
#define AUTOMATE_LEFT_BRAKE_MSG_BRAKE_PUSHED_NAME "Brake_Pushed"
#define AUTOMATE_LEFT_BRAKE_MSG_TIME_TO_END_OPERATION_NAME "Time_to_end_operation"

/**
 * Signals in message Heart_Beat_MSG.
 *
 * All signal values are as on the CAN bus.
 */
struct automate_heart_beat_msg_t {
    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t node_id;

    /**
     * Range: 0..4294967295 (0..4294967295 -)
     * Scale: 1
     * Offset: 0
     */
    uint32_t msg_count;

    /**
     * Range: 0..5 (0..5 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t health;

    /**
     * Range: 0..65535 (0..65535 ms)
     * Scale: 1
     * Offset: 0
     */
    uint16_t stamp;
};

/**
 * Signals in message Left_Brake_CMD.
 *
 * All signal values are as on the CAN bus.
 */
struct automate_left_brake_cmd_t {
    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t msg_id;

    /**
     * Range: 0..65535 (0..65535 ms)
     * Scale: 1
     * Offset: 0
     */
    uint16_t stamp;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t brake_state;
};

/**
 * Signals in message Left_Brake_MSG.
 *
 * All signal values are as on the CAN bus.
 */
struct automate_left_brake_msg_t {
    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t msg_id;

    /**
     * Range: 0..65535 (0..65535 ms)
     * Scale: 1
     * Offset: 0
     */
    uint16_t stamp;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t brake_releasing;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t brake_released;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t brake_pushing;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t brake_pushed;

    /**
     * Range: 0..65535 (0..65535 ms)
     * Scale: 1
     * Offset: 0
     */
    uint16_t time_to_end_operation;
};

/**
 * Pack message Heart_Beat_MSG.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int automate_heart_beat_msg_pack(
    uint8_t *dst_p,
    const struct automate_heart_beat_msg_t *src_p,
    size_t size);

/**
 * Unpack message Heart_Beat_MSG.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int automate_heart_beat_msg_unpack(
    struct automate_heart_beat_msg_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Heart_Beat_MSG.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int automate_heart_beat_msg_init(struct automate_heart_beat_msg_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t automate_heart_beat_msg_node_id_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double automate_heart_beat_msg_node_id_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool automate_heart_beat_msg_node_id_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t automate_heart_beat_msg_msg_count_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double automate_heart_beat_msg_msg_count_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool automate_heart_beat_msg_msg_count_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t automate_heart_beat_msg_health_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double automate_heart_beat_msg_health_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool automate_heart_beat_msg_health_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t automate_heart_beat_msg_stamp_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double automate_heart_beat_msg_stamp_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool automate_heart_beat_msg_stamp_is_in_range(uint16_t value);

/**
 * Pack message Left_Brake_CMD.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int automate_left_brake_cmd_pack(
    uint8_t *dst_p,
    const struct automate_left_brake_cmd_t *src_p,
    size_t size);

/**
 * Unpack message Left_Brake_CMD.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int automate_left_brake_cmd_unpack(
    struct automate_left_brake_cmd_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Left_Brake_CMD.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int automate_left_brake_cmd_init(struct automate_left_brake_cmd_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t automate_left_brake_cmd_msg_id_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double automate_left_brake_cmd_msg_id_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool automate_left_brake_cmd_msg_id_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t automate_left_brake_cmd_stamp_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double automate_left_brake_cmd_stamp_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool automate_left_brake_cmd_stamp_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t automate_left_brake_cmd_brake_state_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double automate_left_brake_cmd_brake_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool automate_left_brake_cmd_brake_state_is_in_range(uint8_t value);

/**
 * Pack message Left_Brake_MSG.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int automate_left_brake_msg_pack(
    uint8_t *dst_p,
    const struct automate_left_brake_msg_t *src_p,
    size_t size);

/**
 * Unpack message Left_Brake_MSG.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int automate_left_brake_msg_unpack(
    struct automate_left_brake_msg_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from Left_Brake_MSG.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int automate_left_brake_msg_init(struct automate_left_brake_msg_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t automate_left_brake_msg_msg_id_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double automate_left_brake_msg_msg_id_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool automate_left_brake_msg_msg_id_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t automate_left_brake_msg_stamp_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double automate_left_brake_msg_stamp_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool automate_left_brake_msg_stamp_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t automate_left_brake_msg_brake_releasing_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double automate_left_brake_msg_brake_releasing_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool automate_left_brake_msg_brake_releasing_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t automate_left_brake_msg_brake_released_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double automate_left_brake_msg_brake_released_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool automate_left_brake_msg_brake_released_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t automate_left_brake_msg_brake_pushing_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double automate_left_brake_msg_brake_pushing_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool automate_left_brake_msg_brake_pushing_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t automate_left_brake_msg_brake_pushed_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double automate_left_brake_msg_brake_pushed_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool automate_left_brake_msg_brake_pushed_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t automate_left_brake_msg_time_to_end_operation_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double automate_left_brake_msg_time_to_end_operation_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool automate_left_brake_msg_time_to_end_operation_is_in_range(uint16_t value);


#ifdef __cplusplus
}
#endif

#endif
